name: Deployment
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2
        with:
          version: 7.27.1
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14.1
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Test Lint
        run: pnpm lint

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ponyo server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /root/project/fontlay
            git pull origin main
            git status
            pnpm install
            pnpm deploy:prod

      # Notification
      - name: Success Notification
        uses: sarisia/actions-status-discord@master
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          status: "Success"
          title: "deploy fontlay 🎉"
          description: "Deploy fontlay front-end to ponyo server."
          color: 0x99FF66
          url: "https://fontlay.com"
      - name: Failed Notification
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@master
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          status: "Failure"
          content: "Hey <@&735080822465495090>"
          title: "deploy fontlay 🥵"
          description: "Failed to deploy fontlay front-end."
          color: 0xF44336
